# Dependencies
markdown:	kramdown

# Permalinks
# permalink:	/blog/:title

# Setup
title:            Fab City Blog
tagline:          'blog'
description:      'Fab City Blog'
url:              http://fabcity.github.io
baseurl:          /blog
commentsystem:    google
disqus:           example

author:
  name:           Fab City
  url:            https://fab.city

paginate:         5


# Custom vars
icon:             assets/images/logo.svg
cover:            assets/images/cover.png

social:
  - icon:         twitter
    url:          https://twitter.com/fabcity
    desc:         Follow me on twitter

  - icon:         github
    url:          https://github.com/fabcity
    desc:         Fork me on github

  - icon:         googleplus-alt
    url:          #https://google.com/+IanCamporezBrunelli
    desc:         Add me on google+

  - icon:         feed
    url:          http://fabcity.github.io/blog/atom.xml 
    desc:         Subscribe to my feed
 
menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:         Fab City
  url:            http://fab.city
  type_title:     Some rights reserved  
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ff0d0d
  secondary: d41111
  secondary-dark: 000

gems: [jekyll-paginate]
